export const metadata = {
  title: "Terms & Conditions",
  description: "Terms and conditions for using the nutrition facts label maker.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16">
      <h1 className="text-3xl font-bold text-neutral-900">Terms &amp; Conditions</h1>
      <div className="mt-6 flex flex-col gap-4 text-sm leading-relaxed text-neutral-700">
        <p>
          By using this website you agree to use the nutrition facts label maker only for lawful purposes and to
          take full responsibility for the accuracy of any data you enter into it.
        </p>
        <p>
          Labels and images generated by this tool are provided for your own use. We make no claim of ownership over
          the nutrition data, product names, or images you supply, and you retain full rights to the labels you
          create.
        </p>
        <p>
          We may update these terms from time to time. Continued use of the site after changes are posted
          constitutes acceptance of the revised terms.
        </p>
      </div>
    </div>
  );
}
